{
  lib,
  config,
  pkgs,
  ...
}: {
  imports = [../../configuration.nix];

  machineType = "desktop";
  hostDir = "/home/rob/repos/dotfiles/hosts/desktop/";

  # Combined audio output for Xonar + D1 DAC
  services.pipewire.extraConfig.pipewire."99-combined-sink" = {
    "context.modules" = [
      {
        name = "libpipewire-module-combine-stream";
        args = {
          "combine.mode" = "sink";
          "node.name" = "combined_xonar_d1";
          "node.description" = "Xonar + D1 DAC (Combined)";
          "combine.props" = {
            "audio.position" = ["FL" "FR"];
          };
          "stream.rules" = [
            {
              matches = [
                {"node.name" = "alsa_output.usb-ASUSTeK_Xonar_SoundCard-00.analog-stereo";}
                {"node.name" = "alsa_output.usb-Audioengine_Audioengine_D1-00.analog-stereo";}
              ];
              actions = {
                create-stream = {};
              };
            }
          ];
        };
      }
    ];
  };

  # Yuzu
  home-manager.users.rob.home.packages = with pkgs; [yuzu-pkgs.pkgs];

  # machine specific hardware information (generated by nix)

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8051a224-3233-49fe-b693-f253740d9b86";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B08D-54DC";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Setting overrides
  networking.interfaces.enp4s0.wakeOnLan.enable = true;
  autoLogin = true;
}
