{...}: {
  imports = [
    ./dolphin.nix
    ./steam.nix
    ./yuzu.nix
    ./slack.nix
    ./protonvpn-gui.nix
    ./ticktick.nix
    ./signal.nix
    ./devenv.nix
    ./spotify.nix
    ./zsh.nix
    ./wdisplays.nix
    ./pavucontrol.nix
    ./discord.nix
    ./anki.nix
    ./vivaldi.nix
    ./aerc.nix
    ./alacritty.nix
    ./aria2.nix
    ./autojump.nix
    ./bash.nix
    ./bat.nix
    ./bottom.nix
    ./broot.nix
    ./btop.nix
    ./carapace.nix
    ./cava.nix
    ./chawan.nix
    ./comodoro.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./firefox.nix
    ./foot.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./gitui.nix
    ./go.nix
    ./htop.nix
    ./imv.nix
    ./java.nix
    ./joshuto.nix
    ./jq.nix
    ./keepassxc.nix
    ./kitty.nix
    ./jj.nix
    ./darktable.nix
    ./lf.nix
    ./mbsync.nix
    ./micro.nix
    ./mpv.nix
    ./msmtp.nix
    ./ncmpcpp.nix
    ./neovim.nix
    ./newsboat.nix
    ./nh.nix
    ./nix-index.nix
    ./nushell.nix
    ./obs.nix
    ./pandoc.nix
    ./password.nix
    ./pistol.nix
    ./pyenv.nix
    ./ripgrep.nix
    ./rofi.nix
    ./rtorrent.nix
    ./sagemath.nix
    ./sioyek.nix
    ./sqls.nix
    ./ssh.nix
    ./superfile.nix
    ./swayimg.nix
    ./swaylock.nix
    ./texlive.nix
    ./tmux.nix
    ./translate.nix
    ./thunderbird.nix
    ./vifm.nix
    ./visidata.nix
    ./vscode.nix
    ./waybar.nix
    ./wofi.nix
    ./xplr.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
