{...}: {
  imports = [
    ./opencode.nix
    ./gemini-cli.nix
    ./google-chrome.nix
    ./forgejo-cli.nix
    ./obsidian.nix
    ./claude-code.nix
    ./glab.nix
    ./dbeaver.nix
    ./proton-auth.nix
    ./protonmail-desktop.nix
    ./jellyfin.nix
    ./vlc.nix
    ./dolphin.nix
    ./steam.nix
    ./slack.nix
    ./protonvpn-gui.nix
    ./ticktick.nix
    ./signal.nix
    ./spotify.nix
    ./zsh.nix
    ./wdisplays.nix
    ./pavucontrol.nix
    ./discord.nix
    ./anki.nix
    ./autojump.nix
    ./bash.nix
    ./btop.nix
    ./cava.nix
    ./direnv.nix
    ./firefox.nix
    ./fzf.nix
    ./git.nix
    ./imv.nix
    ./jq.nix

    ./kitty.nix
    ./jj.nix
    ./darktable.nix
    ./neovim.nix
    ./password.nix
    ./ripgrep.nix
    ./rofi.nix
    ./ssh.nix
    ./swaylock.nix
    ./tmux.nix
    ./vscode.nix
    ./waybar.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
