alias vim="nvim"
alias v="nvim"
alias cl="clear"
alias gcm="git commit"
alias rebuild="zsh -c 'cd ~/repos/dotfiles/nix/nixos ; sudo nixos-rebuild switch --flake .#dev'"
alias rebuild-home="zsh -c 'cd ~/repos/dotfiles/nix/home-manager/ ; home-manager switch -b backup --flake .#rmurphy@dev'"
